function [ lockedFunc ] = LockFunction( callback )
%
%
%%%%%%%%%%%%%%%%55
    lockedFunc = ...
        @(s, params) ...
        (...
            callback(s, params) ./  ...
            ( ...
                1 + ...
                callback(s, params)...
            ) ...
        );

return
end


